/*
 * @Descripttion:
 * @Author: 温祖彪
 * @Date: 2021-11-16 17:24:30
 * @LastEditors: sueRimn
 * @LastEditTime: 2021-11-16 17:24:31
 */
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
setTimeout(() => {
  // 故意抛出一个错误，查看是否可以捕获错误
  console.log(aaa);
}, 0);
